-- Lisää DROP TABLE lauseet tähän tiedostoon
DROP TABLE IF EXISTS Kysymys CASCADE;
DROP TABLE IF EXISTS Vastaukset CASCADE;
DROP TABLE IF EXISTS Vastaus CASCADE;
DROP TABLE IF EXISTS Tulos CASCADE;
DROP TABLE IF EXISTS Kayttaja CASCADE;
DROP TABLE IF EXISTS Puolue CASCADE;
